project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto
  warning: false

lang: id

website:
  title: "Deri Siswara"
  favicon: static/img/logods2.webp
  site-url: https://derisiswara.art
  repo-url: https://github.com/derisiswara/derisiswara.github.io
  open-graph: true
  navbar:
    left:
      - text: About
        file: index.qmd
      - text: Layanan Data
        file: layanan/index.qmd
    right:
      - text: Blog & Proyek
        menu:
          - text: Blog
            icon: journal-text
            file: tulisan/index.qmd
          - text: Proyek
            icon: clipboard-data
            file: projects/index.qmd
      - text: Tutorial
        menu:
          - text: R
            icon: r-circle
            file: tutorial/r/index.qmd
          - text: Python
            icon: filetype-py
            file: tutorial/python/index.qmd
          - text: STATA
            icon: database
            file: tutorial/stata/index.qmd
      - text: Presentasi & Kuliah
        file: materi/index.qmd
      - text: CV
        href: https://derisiswara.art/cv/cv.pdf
  page-footer:
    left: |
      <span class="faux-block">{{< fa copyright >}} 2025–2026 Deri Siswara</span>
    center: |
      [{{< fa brands github >}} GitHub](https://github.com/derisiswara) · 
      [{{< fa brands linkedin >}} LinkedIn](https://www.linkedin.com/in/derisiswara/) · 
      [{{< ai google-scholar >}} Scholar](https://scholar.google.co.id/citations?user=NNhhI5IAAAAJ&hl=en) · 
      [{{< fa envelope >}} Email](mailto:derisiswarads@gmail.com)
    right: |
      <span class="faux-block">Dibuat dengan [Quarto](https://quarto.org/) | [{{< fa brands github >}} Source]({{< var repo-url >}})</span>
      
format:
  html:
    respect-user-color-scheme: false
    theme: 
      light: 
        - static/html/custom.scss
      dark:
        - static/html/custom.scss
        - static/html/dark.scss

bibliography: references.bib




