project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  title: ""
  description: "R code, economics, and data science."
  site-url: https://derisiswara.org/
  favicon: assets/img/logods2.webp
  open-graph:
    locale: en_EN
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    pinned: true
    logo: assets/img/logods2.webp
    left:
      - text: Portfolio
        href: index.qmd
 #     - text: Book Updates
 #       href: book.qmd  
      - text: About
        href: about.qmd
      - text: Workshop RStudio 2025
        href: workshop.qmd

    right:
      - icon: github
        text: GitHub
        href: https://github.com/derisiswara
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/derisiswara/

  page-footer:
    border: true
    left: "&#169; 2025 Deri Siswara"
    center:
      - text: License
        href: license.qmd
    right: "made with [Quarto](https://quarto.org)"
  comments:
    giscus:
      repo: derisiswara/ds_website

format:
  html:
    theme: [flatly, assets/styling/theme.scss]
    toc: true
    toc-depth: 4
    pagetitle: "DS | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y