project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  title: ""
  description: "R code, economics, and data science."
  site-url: https://derisiswara.org/
  favicon: assets/img/logods2.webp
  open-graph:
    locale: en_EN
  page-navigation: true
  back-to-top-navigation: true

  sidebar:
    logo: assets/img/deri.png
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/derisiswara/
        text: "LinkedIn"
      - icon: github
        href: https://github.com/derisiswara
        text: "Github"
      - icon: send
        text: "Email"
        href: mailto:derisiswarads@gmail.com
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: Portfolio
        href: index.qmd
      - text: Book Updates
        href: book/book.qmd
#      - text: CV
#        href: cv/cv.qmd  
        
  page-footer:
    border: true
    left: "&#169; 2025 Deri Siswara"
    center:
      - text: License
        href: license.qmd
    right: "made with [Quarto](https://quarto.org)"
  comments:
    giscus:
      repo: derisiswara/ds_website

format:
  html:
    theme: [cosmo, assets/styling/light.scss]
    toc: true    
    toc-depth: 4
    pagetitle: "{{< meta title >}} - Deri Siswara"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y