project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto
  warning: false

website:
  title: "Deri Siswara"
  favicon: static/img/logods2.webp
  site-url: https://derisiswara.art
  repo-url: https://github.com/derisiswara/derisiswara.github.io
  open-graph: true
  navbar:
    right:
      - text: Projects
        file: projects/index.qmd
      - text: Talks
        file: talks/index.qmd
      - text: CV
        href: https://derisiswara.art/cv/cv.pdf
  page-footer:
    left: |
      <span class="faux-block">{{< fa copyright >}} 2025 Deri Siswara </span>
    center: |
      [License](license.qmd)
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) | Source [{{< fa brands github >}} GitHub]({{< var repo-url >}})</span>
      
format:
  html:
    theme: 
      - static/html/custom.scss

bibliography: references.bib




