---
title: "Curriculum Vitae"
anchor-sections: false
---

<h1 style="font-size: 2.5em;">Hi! I'm <strong>Deri Siswara</strong> 👋</h1>

<span class="listing-btn-group">
<a href="cv/dericv/template/main.pdf" target="_blank" class="btn" role="button"> View CV PDF </a>
</span>

<!-- Professional Summary -->

### <i class="bi bi-person-fill"></i> Professional Summary

Research/Data Analyst with a background in Statistics and Economics. Experienced in survey design, creating dashboards, impact assessment, econometric modeling, and teaching. Worked on various projects across multiple sectors, bringing unique and diverse perspectives to problem-solving.

<!-- Education -->

### <i class="bi bi-mortarboard-fill"></i> Education

-  MSc in Statistics and Data Science, IPB University, 2024
-  Bachelor of Economics, IPB University, 2020

<!-- Professional Experience -->

### <i class="bi bi-briefcase-fill"></i> Work Experience

#### **Perbanas Institute**, Jakarta, ID  

**Adjunct Lecturer** *(February 2025 - June 2025)*  

- Teaching Machine Learning course for the Data Science Program in the Faculty of Information Technology
- Developing curriculum and practical lab sessions for undergraduate students

#### **IPB University**, Bogor, ID  

**Assistant Lecturer** *(February 2021 - December 2024)*  

- Teaching courses including General Economics, Econometrics I, Econometrics II, Quantitative Methods, and Empirical Finance

### <i class="bi bi-clipboard-data-fill"></i> Major Projects

#### **Non-Cash Social Assistance Monitoring Survey 2025**  
**Researcher** *(May 2025 - October 2025)* | Bank Indonesia

- Developed technical guidelines for implementing the Non-Cash Social Assistance Monitoring Survey 2025
- Created data entry tools for survey result collection
- Prepared technical coordination materials for Bank Indonesia's Domestic Representative Offices
- Conducted data processing and analysis of the monitoring survey results

#### **Implementation Study of Food Safety in APEC Regions**  
**Consultant/Data Analyst** *(May 2025 - July 2025)* | APEC Project: SCSC_102_2024T

- Analyzed survey data on food safety management systems for street vendors and small businesses in APEC regions
- Presented findings at a stakeholder workshop in Bali, Indonesia (July 22-23, 2025)

#### **Outlier Detection Study in Banking Report Data**  
**Consultant/Data Analyst** *(June 2024 - March 2025)* | Bank Indonesia

- Researched and implemented various statistical methods for outlier detection in daily and monthly banking report data
- Identified optimal outlier detection methods and thresholds for improving the accuracy of financial reporting systems
- Conducted knowledge sharing sessions

#### **Socio-Economic Impact Analysis of Subsidized Fuel Restrictions**  
**Consultant/Data Analyst** *(February 2024 - August 2024)* | PT Pertamina (Persero)

- Focused on assessing the socio-economic impacts of subsidized fuel restrictions, including effects on poverty, unemployment, inflation, and economic growth
- Applied econometric methods, data analysis, microeconomics principles, and market research techniques

#### **Food Price Analysis**  
**Consultant/Data Analyst** *(May 2023 - November 2023)* | KPPU

- Analyzed the price transmission mechanism of 10 selected commodities using Nonlinear Autoregressive Distributed Lag (NARDL) models

#### **In House Training (IHT)**  
**Trainer** *(October 2022)* | Bank Indonesia Institute (BINS)

- Conducted training on statistics and econometrics tools, covering courses such as univariate time series, multivariate time series, and panel data using RStudio

#### **Customer Classification and Sector Mapping Study**  
**Junior Data Analyst** *(February 2022 - August 2022)* | IPB University and PT. Pegadaian

- Developed customer classification model based on the probability of default using logistic regression
- Conducted sectoral mapping of non-pawned products for each regional office of PT. Pegadaian

<!-- Skills -->

### <i class="bi bi-tools"></i> Skills

-  **Programming Languages**: R, Python, SQL, HTML/CSS, Markdown, Typst
-  **Statistical Software**: EViews, Stata, SPSS, RStudio, Jupyter Notebook
-  **Data Visualization & Publishing**: Tableau, Looker, Quarto
-  Research methods in economics and social sciences
-  Work efficiency

<!-- Publications -->

### <i class="bi bi-journal-bookmark-fill"></i> Publications

<span class="listing-btn-group">
<a href="https://scholar.google.co.id/citations?user=NNhhI5IAAAAJ&hl=id&oi=ao" class="btn" role="button"> My Google Scholar </a>
</span>

**Books:**
-   Metode Kuantitatif dengan RStudio (2024) - IPB Press
-   Aplikasi Model Ekonometrika dengan RStudio (2024) - IPB Press

**Journal Articles:**
-   Classification Modeling with RNN-based, Random Forest, and XGBoost for Imbalanced Data: A Case of Early Crash Detection in ASEAN-5 Stock Markets. (2024). Scientific Journal of Informatics, 11(3), 569-582
-   Regional Tourism Development in Nusa Tenggara Barat: Maximizing Local Economic Development, EcceS: Economics Social and Development Studies 9 (2), 107-127 (2022)

**Other Publications:**
-   Integrasi Pasar Saham Syariah Negara OKI dalam Krisis Pasar Saham Tiongkok dan Perang Dagang AS Tiongkok
-   Pemodelan Klasifikasi dengan RNN-based, Random Forest, dan XGBoost untuk Data Tidak Seimbang: Kasus Deteksi Dini Tekanan di Pasar Modal ASEAN-5
-   Aplikasi Model Ekonometrika dengan RStudio Edisi Kedua
-   Aplikasi Model Ekonometrika dengan RStudio: Model Time-Series, Panel, Spatial

<!-- Honors & Awards -->

### <i class="bi bi-award-fill"></i> Honor & Awards

- Jabar Future Leaders Scholarship [Sep 2021]
- Oral presentation - 12th International Conference on Islamic Economics & Finance [Aug 2020]

<!-- Back to Top Button -->

<button onclick="topFunction()" id="myBtn" title="Go to top">Back to Top</button>

<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0; // For Safari
    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}
</script>