---
title: "Curriculum Vitae"
anchor-sections: false
---
<!-- Education -->

### <i class="bi bi-mortarboard-fill"></i> Education

[**Master of Science in Statistics and Data Science**]{.h5} [Sep 2021 - Aug 2024]{.cv-date}<br>
[*IPB University*]{.h6}

-   [Thesis]{.underline}: [*Classification Modeling with RNN-based, Random Forest, and XGBoost for Imbalanced Data: A Case of Early Crash Detection in ASEAN-5 Stock Markets*](https://scholar.google.co.id/citations?view_op=view_citation&hl=id&user=NNhhI5IAAAAJ&citation_for_view=NNhhI5IAAAAJ:Y0pCki6q_DkC)
-   Honors; Cum Laude

[**Bachelor of Economics in Islamic Economics**]{.h5} [Sep 2016 - Aug 2020]{.cv-date}<br>
[*IPB University*]{.h6}

-   [Thesis]{.underline}: [*The Integration of Islamic Stock Markets of OIC Countries during the China Stock Market Crisis and the US-China Trade War*](https://scholar.google.co.id/citations?view_op=view_citation&hl=id&user=NNhhI5IAAAAJ&citation_for_view=NNhhI5IAAAAJ:2osOgNQ5qMEC)
-   Honors; Cum Laude

[**Non-Formal Education**]{.h4}<br>
[**AI/ML Engineer**]{.h5} [Des 2023 - Des 2024]{.cv-date}<br>
[*Pacmann Academy*]{.h6}

<br>

<!-- Professional Experience -->

### <i class="bi bi-briefcase-fill"></i> Professional Experience

[**Data Consultant**](){.h5} [Jul 2020 – Present]{.cv-date}<br>

Specialized in econometrics and quantitative methods for academic research and policy analysis, adept at using statistical software such as STATA, EViews, R, and Python.

**Contributions:**

- Assist academic researchers with data analysis.
- Deliver webinars, training sessions, and private consultations.
- Conduct research projects for government institutions and ministries.
- Successfully completed over 100 projects.

[**Socio-Economic Impact Analysis of Subsidized Fuel Restrictions**](){.h5} [Feb 2024 - Aug 2024]{.cv-date}<br>
[*PT Pertamina (Persero)*]{.h6}

Focused on assessing the socio-economic impacts of subsidized fuel restrictions, including effects on poverty, unemployment, inflation, and economic growth. 

**Contributions:**

- Performed regression analysis to assess the effects of price changes on inflation and unemployment.
- Employed microsimulation analysis using SUSENAS data to evaluate the impact of fuel restrictions on poverty levels.
- Analyzed input-output data to explore the implications for economic growth.

[**Developed Best Outlier Detection Formula for Integrated Commercial Bank Reports**](){.h5} [Jun 2024]{.cv-date}<br>
[*Bank Indonesia*]{.h6}

The primary focus of this project was introducing various statistical methods for outlier detection. Additionally, the workshop featured hands-on practical sessions using Python. The two-day event was held in Lombok, Indonesia.

**Contributions:**

- Delivered theoretical knowledge on basic programming languages and outlier detection methods, encompassing classical statistics to machine learning and deep learning techniques.
- Led practical sessions to identify and implement the most effective outlier detection method for Integrated Commercial Bank Reports data.

[**Food Price Analysis**](){.h5} [May 2023 - Nov 2023]{.cv-date}<br>
[*Indonesia Competition Commission (KPPU)*]{.h6}

Analyzed the price transmission mechanism of 10 selected commodities by building models using the Nonlinear Autoregressive Distributed Lag (NARDL) model.

**Contributions:**

- Applied NARDL models in R to analyze price transmission mechanisms across 10 selected commodities at the national level, focusing on interactions among producers, wholesalers, traditional markets, and modern markets.
- Conducted training sessions on basic R programming and RStudio, emphasizing the theoretical foundations of ARDL and NARDL models.
- Created project reports and presentations.

[**Statistics and Econometrics In-House Training (IHT)**](){.h5} [Oct 2022]{.cv-date}<br>
[*Bank Indonesia Institute (BINS)*]{.h6}

Conducted training on statistics and econometrics tools, covering courses such as univariate time series, multivariate time series, and panel data using RStudio.

**Contributions:**

- Developed R syntax templates for econometric methods, including ARIMA, ARCH/GARCH, VAR, VECM, and panel data models with both fixed and random effects.
- Assisted doctors and professors as a teaching assistant during practical sessions.

[**Customer Classification and Sector Mapping Study**](){.h5} [Feb 2022 - Aug 2022]{.cv-date}<br>
[*PT. Pegadaian*]{.h6}

Developed customer classification model based on the probability of default using logistic regression. Conducted sectoral mapping of non-pawned products for each regional office of PT. Pegadaian. This analysis provided a foundation for policymaking.

**Contributions:**

- Assisted in data analysis using Excel and STATA.
- Led dissemination and knowledge transfer sessions.


[**Baseline Survey YESS Program**](){.h5} [Jul 2020- Nov 2020]{.cv-date}<br>
[*Ministry of Agriculture*]{.h6}

Worked as a supervisor and research assistant for the Youth Entrepreneurship and Employment Support Services (YESS), a collaborative program between the Ministry of Agriculture and the International Fund for Agricultural Development (IFAD), aimed at developing young entrepreneurs and a reliable workforce in the agricultural sector.

**Contributions:**

- Assisted in field surveys for data collection.
- Conducted data analysis using Excel.
- Wrote comprehensive reports.

<br>

<!-- Skills -->

### <i class="bi bi-tools"></i> Skills

[**Hard Skills**]{.h4}

- [Programming Languages]{.underline}: R, Python, SQL, Markdown
- [Web Development]{.underline}: Quarto
- [Other Software]{.underline}: STATA, EViews, SPSS
- Econometrics with R (*Time Series*, *Panel Data*, *Spatial*, *Survey Data*)
- Machine Learning (*Ensemble Methods*)
- Deep Learning (*RNN*, *GRU*, *LSTM*)
- Data Visualization (*ggplot2*, *plotly*)
- Parameterized Reporting (*R Markdown*, *Quarto*)
- Academic Writing

[**Soft Skills**]{.h4}

- Project Management (*Obsidian*, *Notion*)
- Adaptability
- Problem-Solving
- Work Efficiency

<br>

<!-- Publications -->

### <i class="bi bi-journal-bookmark-fill"></i> Publications

**Undergraduate Thesis**  

- [Integrasi Pasar Saham Syariah Negara OKI dalam Krisis Pasar Saham Tiongkok dan Perang Dagang AS Tiongkok](https://repository.ipb.ac.id/handle/123456789/105498)

**Master Thesis**  

- [Pemodelan Klasifikasi dengan RNN-based, Random Forest, dan XGBoost untuk Data Tidak Seimbang: Kasus Deteksi Dini Tekanan di Pasar Modal ASEAN-5](https://repository.ipb.ac.id/handle/123456789/158240)  
- Code: [GitHub](https://github.com/dekayzz/early-stock-crash-detection-rnns-tree)

**Books**

- [Metode Kuantitatif dengan RStudio](https://ipbpress.com/product/1520-metode-kuantitatif-dengan-rstudio)

- [Aplikasi Model Ekonometrika dengan RStudio Edisi Kedua](https://ipbpress.com/product/633-aplikasi-model-ekonometrika-dengan-rstudio-edisi-kedua)

- [Aplikasi Model Ekonometrika dengan RStudio: Model Time-Series, Panel, Spatial](https://www.youtube.com/watch?v=eVufkjoS1JA)

**Research Paper**  

- [Regional Tourism Development in Nusa Tenggara Barat: Maximizing Local Economic Development, EcceS: Economics Social and Development Studies 9 (2), 107-127](https://journal.uin-alauddin.ac.id/index.php/ecc/article/view/32194)

- [Classification Modeling with RNN-based, Random Forest, and XGBoost for Imbalanced Data: A Case of Early Crash Detection in ASEAN-5 Stock Markets. (2024). Scientific Journal of Informatics, 11(3), 569-582](https://journal.unnes.ac.id/journals/sji/article/view/4067) 


<br>

<!-- Teaching & Advising -->

### <i class="bi bi-info-circle-fill"></i> Teaching & Advising

[**Instructor at QR Lab Training Center**]{.h5} [2022 - Present]{.cv-date}<br> 
[*IPB University – Department of Economics*]

[**Teaching Assistant in Econometrics**]{.h5} [2019 - 2022]{.cv-date}<br>
[*IPB University – Department of Islamic Economics*] 

[**Teaching Assistant in Quantitative Methods**]{.h5} [2019 - 2022]{.cv-date}<br>
[*IPB University – Department of Islamic Economics*]

[**Assistant to Prof. Muhammad Firdaus**]{.h5} [2020 - 2022]{.cv-date}<br>
[*IPB University*]

<br>


<!-- Honors & Awards -->

### <i class="bi bi-award-fill"></i> Honor & Awards

- Jabar Future Leaders Scholarship [Sep 2021]{.cv-date}   
- Oral presentation - 12th International Conference on Islamic Economics & Finance [Aug 2020]{.cv-date}

<br>

<!-- CV PDF (I-Frame) -->

<!-- ### <i class="bi bi-printer-fill"></i> PDF

<iframe 
  width="800" 
  height="800" 
  src="assets/images/Tyler Bonnell 2024 CV.pdf">
</iframe>

<!-- Back to Top Button -->

<button onclick="topFunction()" id="myBtn" title="Go to top">Back to Top</button>

<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0; // For Safari
    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}
</script>